on:
  push:
    branches:
      - master
name: Deploy Website
jobs:
  ftp-deploy:
    name: FTP-Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present

    - name: FTP-Deploy
      uses: gustavpursche/FTP-Deploy-Action@master
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args:
